CREATE OR REPLACE FUNCTION country_by_name(name TEXT)
RETURNS SETOF COUNTRIES ROWS 1
STABLE PARALLEL SAFE CALLED ON NULL INPUT
LANGUAGE sql
AS $function$
    SELECT *
    FROM countries
    WHERE name = $1;
$function$;

CREATE OR REPLACE FUNCTION lowername(COUNTRIES)
RETURNS TEXT
STABLE PARALLEL SAFE RETURNS NULL ON NULL INPUT
LANGUAGE sql
AS $function$
    SELECT lower($1.name);
$function$;
